/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void controls_window_draw(PApplet appc, GWinData data) { //_CODE_:controls_window:341073:
  appc.background(230);
} //_CODE_:controls_window:341073:

public void field_fov_change(GTextField source, GEvent event) { //_CODE_:field_fov:948341:
  fov = float(source.getText());
  update_timer.start(1);
} //_CODE_:field_fov:948341:

public void update_timer_trigger(GTimer source) { //_CODE_:update_timer:775480:
  redraw();
} //_CODE_:update_timer:775480:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Raytracer");
  controls_window = GWindow.getWindow(this, "Controls", 10, 10, 300, 600, JAVA2D);
  controls_window.noLoop();
  controls_window.setActionOnClose(G4P.EXIT_APP);
  controls_window.addDrawHandler(this, "controls_window_draw");
  field_fov = new GTextField(controls_window, 100, 50, 100, 20, G4P.SCROLLBARS_NONE);
  field_fov.setText("75");
  field_fov.setOpaque(true);
  field_fov.addEventHandler(this, "field_fov_change");
  update_timer = new GTimer(this, this, "update_timer_trigger", 500);
  controls_window.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow controls_window;
GTextField field_fov; 
GTimer update_timer; 